language: node_js

node_js:
  - '11.1.0'

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  project-name: 'home'
  local-dir: 'dist/'
  on:
    branch: master
  verbose: true
  fqdn : 'lays147.org'
